import '@/components/Accordions/Accordions.makeswift'
import '@/components/Marquee/Marquee.makeswift'
import '@/components/Tabs/Tabs.makeswift'
import '@/components/BackgroundGradient/BackgroundGradient.makeswift'
import '@/components/FloatingNav/FloatingNav.makeswift'
